### ISSUE TITLE
Sokol build on macOS 

### ISSUE THREAD

**Issue by prime31** [floooh/pacman.zig#1]
I noticed your are building an object file manually for macOS. You don’t have to do that. Zig can compile Sokol metal no problem. Here is what my build file looks like for one of my projects that used Sokol: https://github.com/prime31/zig-upaya/blob/master/src/deps/sokol/build.zig

**Comment by floooh** [comment]
Oh, very helpful indeed! I was trying to pass "-x objective-x" to the Zig compiler and this didn't seem to work. I'll try integrating your changes (the xcrun trick also looks useful).

**Comment by floooh** [comment]
@prime32: btw I found out that omitting the "-std=c99" from the C compiler options is better. On Linux with GCC, "-std=c99" will switch to "strict POSIX" mode which removes some extensions from headers like time.h (I noticed this when using sokol_time.h from Zig). By omitting "-std=c99", gcc will use "-std=gnu99", which automatically includes the latest POSIX extensions.

**Comment by floooh** [comment]
...I'm running into this problem (I'm also on Big Sur):

https://github.com/ziglang/fetch-them-macos-headers/issues/2

With my previous approach of calling system clang it worked though. I'll try to dig a bit deeper.

**Comment by fabioarnold** [comment]
Regarding the xcrun trick, note there's also `std.zig.system.getSDKPath()`: https://github.com/ziglang/zig/blob/6c2e0c2046a4c1d01587cc15ea2f59af32743eb4/lib/std/zig/system/macos.zig#L462

I use it to set the header search path with `-isysroot` here: https://github.com/fabioarnold/nfd-zig/blob/bc7bb0be858b33df34b4091922f3d81a25f8324e/build.zig#L20
