### ISSUE TITLE
build.zig is not compatible with zig 0.11.0-dev 

### ISSUE THREAD

**Issue by nurpax** [floooh/pacman.zig#16]
Zig dev version cannot build the pacman example due to:

```
C:\Users\janne\dev\pacman.zig\build.zig:11:19: error: no field or member function named 'standardReleaseOptions' in 'Build'
    const mode = b.standardReleaseOptions();
                 ~^~~~~~~~~~~~~~~~~~~~~~~
C:\Users\janne\scoop\apps\zig-dev\current\lib\std\Build.zig:1:1: note: struct declared here
const std = @import("std.zig");
^~~~~
referenced by:
    runBuild__anon_6441: C:\Users\janne\scoop\apps\zig-dev\current\lib\std\Build.zig:1583:27
    steps__anon_6221: C:\Users\janne\scoop\apps\zig-dev\current\lib\build_runner.zig:268:20
    remaining reference traces hidden; use '-freference-trace' to see all reference traces
```

I think there's been a backwards incompatible change to the build options.

I got pacman building on zig 0.10 and the install/build experience was great there :)

**Comment by nurpax** [comment]
First time I tried building anything on Zig so I don't know, but it looks like 0.10 is the latest official release.

I'll take a crack at updating the pacman project for these changes. :)

**Comment by floooh** [comment]
Fixed via merging into new branch https://github.com/floooh/pacman.zig/tree/zig-0.11.0
