### ISSUE TITLE
aarch64: map incorrectly displayed

### ISSUE THREAD

**Issue by kubkon** [floooh/pacman.zig#8]
Here's the output when built against Monterey SDK on `arm64`:

<img width="447" alt="Screenshot 2021-10-25 at 18 15 19" src="https://user-images.githubusercontent.com/1519747/138732445-76005f99-ecf1-4043-b2f7-09db4f51c346.png">

For the record, it used to work fine on BigSur on both `arm64` and `x86_64`.

**Comment by floooh** [comment]
Since it looks like it's an upstream bug in LLVM which will probably take a while to fix I have replaced the use of @Vector() with a regular struct now (https://github.com/floooh/pacman.zig/commit/c0c1f4ae899c605deba24cc499c9aff225d54c05).
